export const SET_RELATIONSHIPS = "SET_RELATIONSHIPS";

export const ADD_RELATIONSHIP = "ADD_RELATIONSHIP";
export const REMOVE_RELATIONSHIP = "REMOVE_RELATIONSHIP";
export const UPDATE_RELATIONSHIP = "UPDATE_RELATIONSHIP";

export const ADD_RELATIONSHIPS = "ADD_RELATIONSHIPS";
export const REMOVE_RELATIONSHIPS = "REMOVE_RELATIONSHIPS";
