export const ADD_RELATIONSHIP = "ADD_RELATIONSHIP";
export const REMOVE_RELATIONSHIP = "REMOVE_RELATIONSHIP";

export const ADD_RELATIONSHIPS = "ADD_RELATIONSHIPS";
export const REMOVE_RELATIONSHIPS = "REMOVE_RELATIONSHIPS";

export const CREATE_RELATED_ITEM = "CREATE_RELATED_ITEM";
export const DESTROY_ITEM = "DESTROY_ITEM";
