export const ADD_VIEW_FOR_SUBITEM = "ADD_VIEW_FOR_SUBITEM";
export const REMOVE_VIEW_FOR_SUBITEM = "REMOVE_VIEW_FOR_SUBITEM";

export const ADD_VIEW_FOR_SUBITEMS = "ADD_VIEW_FOR_SUBITEMS";
export const REMOVE_VIEW_FOR_SUBITEMS = "REMOVE_VIEW_FOR_SUBITEMS";
