export const ADD_RELATIONSHIP_FOR_ITEM = "ADD_RELATIONSHIP_FOR_ITEM";
export const REMOVE_RELATIONSHIP_FOR_ITEM = "REMOVE_RELATIONSHIP_FOR_ITEM";

export const ADD_RELATIONSHIPS_FOR_ITEM = "ADD_RELATIONSHIPS_FOR_ITEM";
export const REMOVE_RELATIONSHIPS_FOR_ITEM = "REMOVE_RELATIONSHIPS_FOR_ITEM";
